// AUTHENTICATION
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

// INCIDENTS
export const GET_INCIDENTS = 'GET_INCIDENTS';
export const SAVE_INCIDENTS = 'SAVE_INCIDENTS';
export const ADD_INCIDENT = 'ADD_INCIDENT';

// WORK REQUESTS
export const GET_WORK_REQUESTS = 'GET_WORK_REQUESTS';
export const SAVE_WORK_REQUESTS = 'SAVE_WORK_REQUESTS';