// AUTHENTICATION
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const SAVE_CURRENT_LOGGED = 'SAVE_CURRENT_LOGGED';
export const REMOVE_CURRENT_LOGGED = 'SAVE_CURRENT_LOGGED';
export const GET_UNAPPROVED_USERS = 'GET_UNAPPROVED_USERS';
export const SAVE_UNAPPROVED_USERS = 'SAVE_UNAPPROVED_USERS';
export const APPROVE_USER = 'APPROVE_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_CLANS = 'GET_CLANS';
export const SAVE_CLANS = 'SAVE_CLANS';

// INCIDENTS
export const GET_INCIDENTS = 'GET_INCIDENTS';
export const SAVE_INCIDENTS = 'SAVE_INCIDENTS';
export const ADD_INCIDENT = 'ADD_INCIDENT';
export const SAVE_EDIT_INCIDENT = 'SAVE_EDIT_INCIDENT';
export const DELETE_EDIT_INCIDENT = 'DELETE_EDIT_INCIDENT';
export const SAVE_DETAILS = 'SAVE_DETAILS';
export const SORT_INCIDENTS = 'SORT_INCIDENTS';
export const SAVE_BASIC_INFO = 'SAVE_BASIC_INFO';

// RESOLUTIONS
export const GET_RESOLUTION_FOR_INCIDENT = 'GET_RESOLUTION_FOR_INCIDENT';
export const SAVE_RESOLUTION_FOR_INCIDENT = 'SAVE_RESOLUTION_FOR_INCIDENT';
export const ADD_RESOLUTION = 'ADD_RESOLUTION';

// WORK REQUESTS
export const GET_WORK_REQUESTS = 'GET_WORK_REQUESTS';
export const SAVE_WORK_REQUESTS = 'SAVE_WORK_REQUESTS';

// CALLS
export const GET_CALLS = 'GET_CALLS';
export const SAVE_CALLS = 'SAVE_CALLS';
export const ADD_CALL = 'ADD_CALL';

// DEVICES
export const ADD_DEVICE = 'ADD_DEVICE';
export const GET_DEVICES = 'GET_DEVICES';
export const GET_ALL_DEVICES = 'GET_ALL_DEVICES';
export const SAVE_DEVICES = 'SAVE_DEVICES';
export const DELETE_DEVICE = 'DELETE_DEVICE';

// YANDEX MAPS
export const GET_COORDINATES = 'GET_COORDINATES';

// NOTIFICATIONS
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const SAVE_NOTIFICATIONS = 'SAVE_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// CREWS
export const GET_CREWS = 'GET_CREWS';
export const SAVE_CREWS = 'SAVE_CREWS'
export const GET_CURRENT_CREW = 'GET_CURRENT_CREW';
export const SAVE_CURRENT_CREW = 'SAVE_CURRENT_CREW';
export const ASSIGN_CREW = 'ASSIGN_CREW';
export const ASSIGN_USER_TO_CREW = 'ASSIGN_USER_TO_CREW';