// AUTHENTICATION
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const SAVE_CURRENT_LOGGED = 'SAVE_CURRENT_LOGGED';
export const REMOVE_CURRENT_LOGGED = 'SAVE_CURRENT_LOGGED';
export const GET_UNAPPROVED_USERS = 'GET_UNAPPROVED_USERS';
export const SAVE_UNAPPROVED_USERS = 'SAVE_UNAPPROVED_USERS';
export const APPROVE_USER = 'APPROVE_USER';

// INCIDENTS
export const GET_INCIDENTS = 'GET_INCIDENTS';
export const SAVE_INCIDENTS = 'SAVE_INCIDENTS';
export const ADD_INCIDENT = 'ADD_INCIDENT';
export const ADD_RESOLUTION = 'ADD_RESOLUTION';

// WORK REQUESTS
export const GET_WORK_REQUESTS = 'GET_WORK_REQUESTS';
export const SAVE_WORK_REQUESTS = 'SAVE_WORK_REQUESTS';

// CALLS
export const GET_CALLS = 'GET_CALLS';
export const SAVE_CALLS = 'SAVE_CALLS';

// DEVICES
export const ADD_DEVICE = 'ADD_DEVICE';
export const GET_DEVICES = 'GET_DEVICES';
export const SAVE_DEVICES = 'SAVE_DEVICES';